import { CreateServiceDto } from './entities/service.entity'

export const DEFAULT_CATALOG_SERVICES: CreateServiceDto[] = [
  {
    title: 'Systems Digitalization',
    description: 'Transform manual processes into efficient digital workflows',
    category: 'Digital Transformation',
    price: 3500,
    features: [
      'Process Analysis & Mapping',
      'Digital Workflow Design',
      'System Integration',
      'Staff Training',
      'Documentation & Support',
    ],
    icon: 'ComputerDesktopIcon',
    status: 'active',
    duration: '4-6 weeks',
    currency: 'USD',
    keyBenefits: [
      'Increased Efficiency',
      'Reduced Manual Errors',
      'Better Data Management',
      'Cost Savings',
    ],
    targetMarket: ['SMEs', 'Government Offices', 'NGOs'],
    deliverables: [
      'Digital Process Documentation',
      'Custom Software Solution',
      'Training Materials',
      '3 Months Support',
    ],
    setupFee: 3500,
    displayOrder: 1,
  },
  {
    title: 'ERP Systems',
    description: 'Enterprise Resource Planning systems for SMEs, schools, SMBs, and hospitals',
    category: 'Enterprise Solutions',
    price: 8000,
    features: [
      'Integrated ERP',
      'Accounting Integration',
      'HR Management',
      'Procurement System',
      'Inventory Management',
    ],
    icon: 'BuildingOfficeIcon',
    status: 'active',
    duration: '8-12 weeks',
    currency: 'USD',
    keyBenefits: [
      'Centralized Operations',
      'Real-time Reporting',
      'Compliance Management',
      'Scalable Solution',
    ],
    targetMarket: ['Schools', 'NGOs', 'Hospitals', 'Retail Businesses'],
    deliverables: [
      'Complete ERP System',
      'Data Migration',
      'User Training',
      '6 Months Support',
    ],
    setupFee: 8000,
    monthlyFee: 200,
    displayOrder: 2,
  },
]
